// import Layout from '@/components/Layout'
// import Head from 'next/head'
// import Image from "next/image"
// import profilePicture from "../../public/images/profile/developer-pic-1.png"
// import AnimatedText from '@/components/AnimatedText'

// export default function Home () {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name='description' content='Generated by create next app' />

//       </Head>
//       <main className='flex items-center text-dark w-full min-h-screen'>
//         <Layout className='pt-0'>
//           <div className='flex items-center justify-between w-full'>
//             {/* width half of container  w-1/2*/}
//             <div className='w-1/2'>
//               <Image src={profilePicture} alt="CodeImage" className="w-full h-auto" />
//             </div>
//           </div>
//         <div className='w-1/2 flex flex-col items-center self-center'>
//           {/* <h1>Turning Vision Into Reality With Code And Design</h1> */}
//           <AnimatedText text="Turning Vision Into Reality With Code And Design" className='!text-6xl !text-left'/>
//           <p>
//             As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications.
// Explore my latest projects and articles, showcasing my expertise in React.js and web development.</p>
//          </div>
//         </Layout></main>
//     </>
//   )
// }
import React from 'react'
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePicture from '../../public/images/profile/developer-pic-1.png'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'

export default function Home () {
  return (
    <>
      {/* Meta-data  */}
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      {/* Main content */}
      <Layout>
        <div className='flex items-center justify-between w-full'>
          {/* Left part with image */}
          <div className='w-1/2'>
            <Image
              src={profilePicture}
              alt='CodeImage'
              className='w-full h-auto'
            />
          </div>

          {/* Right part witn text */}
          <div className='w-1/2 flex flex-col items-center self-center'>
            {/* animated text */}
            <AnimatedText
              text='Transforming Ideas Into Real Web Solutions with Code and Design Excellence'
              className='!text-6xl !text-left'
            />

            {/* Text */}
            <p className='my-4 text-base font-medium'>
              As an aspiring full-stack developer, I am enthusiastic about
              learning and dedicated to turning creative ideas into innovative
              web applications. My passion for web development drives me to
              explore and expand my skills in both front-end and back-end
              technologies. Explore my latest projects and articles, showcasing
              my expertise in React.js and web development.
            </p>
            <div className='flex items-center self-start mt-2'>
              {/* target={'_blank'} - open in the new tab */}
              <Link href='/dummy.pdf' target={'_blank'} 
              className='flex items-center bg-dark text-light p-2.5 px-6 
              rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
              border-2 border-solid border-transparent hover:border-dark
              ' download={true}>Resume <LinkArrow className={"w-6 ml-1"}/></Link>
              <Link href='mailto:abcd@gmail.com' target={'_blank'}  className='flex items-center  ml-4 p-2.5 px-6 
              rounded-lg text-lg font-semibold 
              border-2 border-solid border-transparent hover:border-dark underline
              '>Contact</Link>
            </div>
          </div>
        </div>
      </Layout>
      <HireMe/>
      <div>
        <Image src="" alt="Volodymyr Moroz" className='w-full h-auto'/>
      </div>
    </>
  )
}
